// src/lib/components/molecules/ConfirmDialog.svelte
<script lang="ts">
  import Dialog from '../atoms/Dialog.svelte';
  import Button from '../atoms/Button.svelte';
  import { AlertTriangle } from 'lucide-svelte';

  interface Props {
    open?: boolean;
    title?: string;
    description?: string;
    confirmText?: string;
    cancelText?: string;
    variant?: 'danger' | 'primary';
    onconfirm?: () => void;
    oncancel?: () => void;
  }

  let {
    open = $bindable(false),
    title = 'Confirm Action',
    description = 'Are you sure you want to proceed?',
    confirmText = 'Confirm',
    cancelText = 'Cancel',
    variant = 'danger',
    onconfirm,
    oncancel,
  }: Props = $props();

  function handleConfirm() {
    onconfirm?.();
    open = false;
  }

  function handleCancel() {
    oncancel?.();
    open = false;
  }
</script>

<Dialog bind:open {title} maxWidth="max-w-md" onclose={handleCancel}>
  <div class="flex items-start gap-4">
    <div class="p-3 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-400 flex-shrink-0">
      <AlertTriangle class="w-6 h-6" />
    </div>
    <div>
      <p class="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">{description}</p>
    </div>
  </div>

  <div class="flex items-center justify-end gap-3 mt-6 pt-4 border-t border-slate-100 dark:border-slate-800">
    <Button variant="secondary" size="sm" onclick={handleCancel}>
      {cancelText}
    </Button>
    <Button variant={variant === 'danger' ? 'danger' : 'primary'} size="sm" onclick={handleConfirm}>
      {confirmText}
    </Button>
  </div>
</Dialog>

// components/molecules/ConfirmDialog.tsx
import React from 'react';
import { AlertTriangle, Trash2, X } from 'lucide-react';
import { Button } from '../atoms/Button';

interface ConfirmDialogProps {
  isOpen: boolean;
  title: string;
  message: string;
  confirmLabel?: string;
  cancelLabel?: string;
  variant?: 'danger' | 'warning' | 'primary';
  icon?: React.ReactNode;
  onConfirm: () => void;
  onCancel: () => void;
}

export const ConfirmDialog: React.FC<ConfirmDialogProps> = ({
  isOpen,
  title,
  message,
  confirmLabel = 'Confirm',
  cancelLabel = 'Cancel',
  variant = 'danger',
  icon,
  onConfirm,
  onCancel,
}) => {
  if (!isOpen) return null;

  const defaultIcon = (
    <div
      className={`w-12 h-12 rounded-2xl flex items-center justify-center ${
        variant === 'danger'
          ? 'bg-rose-50 text-rose-600'
          : variant === 'warning'
          ? 'bg-amber-50 text-amber-600'
          : 'bg-blue-50 text-blue-600'
      }`}
    >
      {variant === 'danger' ? <Trash2 className="w-6 h-6" /> : <AlertTriangle className="w-6 h-6" />}
    </div>
  );

  return (
    <div
      id="confirm-dialog-overlay"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-150"
      onClick={onCancel}
    >
      <div
        id="confirm-dialog-content"
        className="bg-white rounded-3xl shadow-2xl border border-slate-100 w-full max-w-md overflow-hidden animate-in zoom-in-95 duration-150 p-6 space-y-5"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3.5">
            {icon || defaultIcon}
            <div>
              <h3 className="text-base font-bold text-slate-900">{title}</h3>
              <p className="text-xs text-slate-500 mt-0.5">Please confirm this action</p>
            </div>
          </div>
          <button
            onClick={onCancel}
            className="p-1.5 text-slate-400 hover:text-slate-600 rounded-xl hover:bg-slate-100 transition-colors cursor-pointer"
            aria-label="Close dialog"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="bg-slate-50 p-3.5 rounded-2xl border border-slate-200/80 text-xs text-slate-700 leading-relaxed">
          {message}
        </div>

        <div className="flex items-center justify-end gap-2.5 pt-1">
          <Button variant="outline" size="sm" onClick={onCancel}>
            {cancelLabel}
          </Button>
          <Button
            variant={variant === 'danger' ? 'danger' : variant === 'warning' ? 'secondary' : 'primary'}
            size="sm"
            onClick={onConfirm}
          >
            {confirmLabel}
          </Button>
        </div>
      </div>
    </div>
  );
};
