// src/lib/components/atoms/StatusIndicator.svelte
<script lang="ts">
  import type { OutreachStatus, SkipTraceStatus } from '../../types/lead';

  interface Props {
    status: OutreachStatus | SkipTraceStatus | string;
    type?: 'outreach' | 'skiptrace';
  }

  let { status, type = 'outreach' }: Props = $props();

  const config = $derived.by(() => {
    switch (status) {
      case 'Uncontacted':
        return { dot: 'bg-[var(--fm-text-muted)]', text: 'text-[var(--fm-text-secondary)]', label: 'Uncontacted' };
      case 'Skip Traced':
      case 'Traced':
        return { dot: 'bg-emerald-400 animate-pulse', text: 'text-emerald-600 dark:text-emerald-400', label: 'Skip Traced' };
      case 'Site Built':
        return { dot: 'bg-cyan-400', text: 'text-cyan-600 dark:text-cyan-400', label: 'Site Built' };
      case 'Outreach Sent':
        return { dot: 'bg-amber-400', text: 'text-amber-600 dark:text-amber-400', label: 'Outreach Sent' };
      case 'In Discussion':
        return { dot: 'bg-purple-400', text: 'text-purple-600 dark:text-purple-400', label: 'In Discussion' };
      case 'Client Won':
        return { dot: 'bg-emerald-300', text: 'text-emerald-700 dark:text-emerald-300 font-bold', label: 'Client Won' };
      case 'Declined':
        return { dot: 'bg-rose-500', text: 'text-rose-600 dark:text-rose-400', label: 'Declined' };
      case 'In Progress':
        return { dot: 'bg-amber-400 animate-ping', text: 'text-amber-600 dark:text-amber-300', label: 'Tracing...' };
      case 'Not Traced':
        return { dot: 'bg-[var(--fm-text-secondary)]', text: 'text-[var(--fm-text-muted)]', label: 'Untraced' };
      default:
        return { dot: 'bg-[var(--fm-text-muted)]', text: 'text-[var(--fm-text-secondary)]', label: status };
    }
  });
</script>

<div class="inline-flex items-center gap-1.5 text-xs font-medium {config.text}">
  <span class="w-2 h-2 rounded-full {config.dot}"></span>
  <span>{config.label}</span>
</div>

// components/atoms/StatusIndicator.tsx
import React from 'react';
import { OutreachStatus } from '../../types/lead';

interface StatusIndicatorProps {
  status: OutreachStatus;
  showText?: boolean;
}

export const StatusIndicator: React.FC<StatusIndicatorProps> = ({ status, showText = true }) => {
  const statusConfig: Record<OutreachStatus, { label: string; dotColor: string; textColor: string; bg: string }> = {
    Uncontacted: { label: 'Discovered', dotColor: 'bg-slate-400', textColor: 'text-slate-700', bg: 'bg-slate-50 border-slate-200' },
    'Skip Traced': { label: 'Skip Traced', dotColor: 'bg-sky-500', textColor: 'text-sky-700', bg: 'bg-sky-50 border-sky-200' },
    'Site Built': { label: 'Site Built', dotColor: 'bg-indigo-500', textColor: 'text-indigo-700', bg: 'bg-indigo-50 border-indigo-200' },
    'Outreach Sent': { label: 'Outreach Sent', dotColor: 'bg-amber-500', textColor: 'text-amber-700', bg: 'bg-amber-50 border-amber-200' },
    'In Discussion': { label: 'In Talks', dotColor: 'bg-purple-500', textColor: 'text-purple-700', bg: 'bg-purple-50 border-purple-200' },
    'Client Won': { label: 'Client Won', dotColor: 'bg-emerald-500', textColor: 'text-emerald-700', bg: 'bg-emerald-50 border-emerald-200' },
    Declined: { label: 'Declined', dotColor: 'bg-rose-400', textColor: 'text-rose-700', bg: 'bg-rose-50 border-rose-200' },
  };

  const config = statusConfig[status] || statusConfig.Uncontacted;

  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full border text-xs font-semibold ${config.bg} ${config.textColor}`}>
      <span className={`w-2 h-2 rounded-full ${config.dotColor} animate-pulse`} />
      {showText && config.label}
    </span>
  );
};
