// components/molecules/Toast.tsx
import React, { useEffect } from 'react';
import { CheckCircle2, AlertTriangle, AlertCircle, Info, X } from 'lucide-react';

export type ToastType = 'success' | 'error' | 'warning' | 'info';

export interface ToastMessage {
  id: string;
  type: ToastType;
  title: string;
  description?: string;
  action?: {
    label: string;
    onClick: () => void;
  };
  duration?: number;
}

interface ToastProps {
  toast: ToastMessage;
  onDismiss: (id: string) => void;
}

export const Toast: React.FC<ToastProps> = ({ toast, onDismiss }) => {
  const duration = toast.duration ?? 4500;

  useEffect(() => {
    if (duration <= 0) return;
    const timer = setTimeout(() => {
      onDismiss(toast.id);
    }, duration);
    return () => clearTimeout(timer);
  }, [toast.id, duration, onDismiss]);

  const iconMap: Record<ToastType, React.ReactNode> = {
    success: <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />,
    error: <AlertCircle className="w-5 h-5 text-rose-600 shrink-0" />,
    warning: <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" />,
    info: <Info className="w-5 h-5 text-blue-600 shrink-0" />,
  };

  const containerStyleMap: Record<ToastType, string> = {
    success: 'bg-white border-emerald-200 text-slate-900 shadow-lg shadow-emerald-950/5',
    error: 'bg-white border-rose-200 text-slate-900 shadow-lg shadow-rose-950/5',
    warning: 'bg-white border-amber-200 text-slate-900 shadow-lg shadow-amber-950/5',
    info: 'bg-white border-blue-200 text-slate-900 shadow-lg shadow-blue-950/5',
  };

  return (
    <div
      id={`toast-${toast.id}`}
      role="status"
      aria-live="polite"
      className={`flex items-start gap-3 p-4 rounded-2xl border ${containerStyleMap[toast.type]} min-w-[320px] max-w-md pointer-events-auto transition-all animate-in fade-in slide-in-from-top-2 duration-200`}
    >
      {iconMap[toast.type]}
      <div className="flex-1 min-w-0 pr-1">
        <h4 className="text-sm font-bold text-slate-900">{toast.title}</h4>
        {toast.description && (
          <p className="text-xs text-slate-600 mt-0.5 leading-relaxed">{toast.description}</p>
        )}
        {toast.action && (
          <button
            onClick={() => {
              toast.action?.onClick();
              onDismiss(toast.id);
            }}
            className="mt-2 text-xs font-bold text-blue-600 hover:text-blue-800 bg-blue-50 hover:bg-blue-100 px-2.5 py-1 rounded-lg transition-colors cursor-pointer inline-flex items-center gap-1"
          >
            {toast.action.label}
          </button>
        )}
      </div>
      <button
        onClick={() => onDismiss(toast.id)}
        className="text-slate-400 hover:text-slate-600 p-1 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer -mr-1 -mt-1"
        aria-label="Close notification"
      >
        <X className="w-4 h-4" />
      </button>
    </div>
  );
};

interface ToastContainerProps {
  toasts: ToastMessage[];
  onDismiss: (id: string) => void;
}

export const ToastContainer: React.FC<ToastContainerProps> = ({ toasts, onDismiss }) => {
  if (toasts.length === 0) return null;

  return (
    <div
      id="toast-notifications-container"
      className="fixed top-4 right-4 z-50 flex flex-col gap-2.5 pointer-events-none max-w-sm w-full"
    >
      {toasts.map((toast) => (
        <Toast key={toast.id} toast={toast} onDismiss={onDismiss} />
      ))}
    </div>
  );
};

// src/lib/components/molecules/Toast.svelte
<script lang="ts">
  import { toast } from '../../stores/toast.svelte';
  import { CheckCircle2, AlertCircle, Info, AlertTriangle, X, Loader2 } from 'lucide-svelte';
</script>

{#if toast.toasts.length > 0}
  <div class="fixed bottom-5 right-5 z-50 flex flex-col gap-2.5 max-w-sm w-full pointer-events-none">
    {#each toast.toasts as item (item.id)}
      <div
        class="pointer-events-auto relative flex items-start gap-3.5 p-4 rounded-xl border backdrop-blur-xl shadow-2xl transition-all animate-in fade-in slide-in-from-bottom-5 duration-200 {item.type === 'success' ? 'bg-white dark:bg-slate-950/95 border-emerald-300 dark:border-emerald-500/40 text-slate-900 dark:text-white shadow-emerald-950/30' : item.type === 'error' ? 'bg-white dark:bg-slate-950/95 border-rose-300 dark:border-rose-500/40 text-slate-900 dark:text-white shadow-rose-950/30' : item.type === 'warning' ? 'bg-white dark:bg-slate-950/95 border-amber-300 dark:border-amber-500/40 text-slate-900 dark:text-white shadow-amber-950/30' : item.type === 'loading' ? 'bg-white dark:bg-slate-950/95 border-emerald-200 dark:border-emerald-500/30 text-slate-900 dark:text-white shadow-emerald-950/20' : 'bg-white dark:bg-slate-950/95 border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white shadow-black/60'}"
      >
        <!-- Icon -->
        <div class="flex-shrink-0 mt-0.5">
          {#if item.type === 'success'}
            <CheckCircle2 class="w-4 h-4 text-emerald-400" />
          {:else if item.type === 'error'}
            <AlertCircle class="w-4 h-4 text-rose-400" />
          {:else if item.type === 'warning'}
            <AlertTriangle class="w-4 h-4 text-amber-400" />
          {:else if item.type === 'loading'}
            <Loader2 class="w-4 h-4 text-emerald-400 animate-spin" />
          {:else}
            <Info class="w-4 h-4 text-sky-400" />
          {/if}
        </div>

        <!-- Content -->
        <div class="flex-grow min-w-0 pr-1">
          <div class="text-xs font-bold text-slate-900 dark:text-white tracking-tight leading-snug">{item.title}</div>
          {#if item.description}
            <div class="text-[11px] text-slate-600 dark:text-slate-300/90 mt-0.5 leading-relaxed break-words font-sans">{item.description}</div>
          {/if}

          {#if item.action}
            <div class="mt-2">
              <button
                type="button"
                onclick={() => {
                  item.action?.onClick();
                  toast.dismiss(item.id);
                }}
                class="text-[11px] font-semibold px-2.5 py-1 rounded-md bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-emerald-700 dark:text-emerald-300 border border-slate-200 dark:border-slate-700 transition-colors cursor-pointer"
              >
                {item.action.label}
              </button>
            </div>
          {/if}
        </div>

        <!-- Dismiss Button -->
        <button
          type="button"
          onclick={() => toast.dismiss(item.id)}
          aria-label="Dismiss notification"
          class="flex-shrink-0 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 p-1 rounded-md transition-colors cursor-pointer -mr-1 -mt-1"
        >
          <X class="w-3.5 h-3.5" />
        </button>
      </div>
    {/each}
  </div>
{/if}
